project/urls.py
from django.contrib import admin
from django.urls import path, include

from project.views import AccountLogoutConfirmationView, AccountLoginView, AccountLoginConfirmationView, \
    AccountLogoutView, AccountLogoutYesNoView, HomePageRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageRedirectView.as_view(), name='home'),
    path('replacement/', include('replacement.urls')),
    # Login/logout
    path('login/', AccountLoginView.as_view(), name='login'),
    path('login-confirmation/', AccountLoginConfirmationView.as_view(), name='login-confirmation'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('logout-yes-no/', AccountLogoutYesNoView.as_view(), name='logout-yes-no'),
    path('logout-confirmation/', AccountLogoutConfirmationView.as_view(), name='logout-confirmation'),

]

replacement/urls.py
from django.urls import path

from replacement.views import KfcListingView, StarbucksListingView, \
    BurgerkingListingView, PizzahutListingView, ReplacementCalculationView, HardwareUpdateView, HardwareCreateView, \
    HomePageTemplateView, HardwareDeleteView, HardwareDetailListingView

app_name = 'replacement'

urlpatterns = [
    path('', HomePageTemplateView.as_view(), name='home-page'),
    path('kfc/', KfcListingView.as_view(), name='kfc-list'),
    path('sbx/', StarbucksListingView.as_view(), name='sbx-list'),
    path('bk/', BurgerkingListingView.as_view(), name='bk-list'),
    path('ph/', PizzahutListingView.as_view(), name='ph-list'),
    path('form/<int:pk>/', ReplacementCalculationView.as_view(), name='replacement-calculation'),
    path('hw-update/<int:pk>/', HardwareUpdateView.as_view(), name='hw-update'),
    path('hw-create/', HardwareCreateView.as_view(), name='hw-create'),
    path('hardware-delete/<int:pk>/', HardwareDeleteView.as_view(), name='hw-delete'),
    path('hw-detail/<int:pk>/', HardwareDetailListingView.as_view(), name='hw-detail'),
]

replacement/forms.py
from django import forms
from django.core.exceptions import ValidationError

import replacement
from replacement.models import Hardware
from datetime import datetime
from dateutil.relativedelta import relativedelta


class ReplacementForm(forms.ModelForm):
    """
    Form for calculating whether hardware should be replaced.
    Includes fields for repair offer, service cost, and hardware production date.
    """
    repair_offer = forms.DecimalField(label='Cenová nabídka', max_digits=10, decimal_places=2, help_text="Zadej cenovou nabídku na opravu")
    service_cost = forms.DecimalField(label='Částka za opravy', max_digits=10, decimal_places=2, help_text="Zadej kolik stály minulé opravy")
    hw_production_date = forms.DateField(
        label='Výrobní datum',
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
        help_text="Zadej datum výroby stroje"
    )

    class Meta:
        model = Hardware
        fields = ['repair_offer', 'service_cost', 'hw_production_date']

    def clean_hw_production_date(self):
        """
        Validates the production date to ensure it is in the past.

        :raises ValidationError: If the production date is in the future.
        :return: Cleaned hardware production date.
        """
        hw_production_date = self.cleaned_data.get('hw_production_date')
        today = datetime.today().date()

        if isinstance(hw_production_date, datetime):
            hw_production_date = hw_production_date.date()

        # Ensure the production date is not in the future.
        if hw_production_date > today:
            raise ValidationError("Datum výroby musí být v minulosti.")

        return hw_production_date


    def calculate(self, hardware):
        """
        Performs the replacement calculation based on the hardware's age, repair costs, and other factors.

        :param hardware: Hardware instance used for calculations.
        :return: Tuple containing the replacement calculation value and the corresponding message.
        """
        # Calculate the age of the hardware in months
        today = datetime.today().date()
        hw_production_date = self.cleaned_data['hw_production_date']

        if isinstance(hw_production_date, datetime):
            hw_production_date = hw_production_date.date()

        hardware_age = relativedelta(today, hw_production_date).years * 12 + relativedelta(today,
                                                                                           hw_production_date).months

        # Calculate the residual value of the hardware
        write_off_length = hardware.write_off_length
        remaining_months = max(0, write_off_length * 12 - hardware_age)
        residual_value = float((remaining_months / (write_off_length * 12)) * hardware.hw_price)

        # Gather other necessary values
        repair_offer = float(self.cleaned_data['repair_offer'])
        service_cost = float(self.cleaned_data['service_cost'])

        # Perform the replacement equation
        ers = repair_offer + service_cost
        kpc = hardware.hw_price * 0.2
        tbo = 0 if hardware_age < 60 else (hardware_age - 60) / 3
        ezh = ((residual_value + 1) / hardware.hw_price) * 100
        replacement_calculation = int(((ers - kpc) / 1000) + tbo - ezh)


        rounded_replacement_calculation = round(replacement_calculation, 2)

        print(rounded_replacement_calculation)

        # Final message for the user based on the replacement calculation
        if rounded_replacement_calculation > 10:
            message = f"Replacement proběhne, oprava je nákladná. Výsledek rovnice je {rounded_replacement_calculation}."
        elif -10 < rounded_replacement_calculation < 10:
            message = f"Je to na individuálním posouzení, výsledek rovnice je {rounded_replacement_calculation}."
        else:
            message = f"Replacement neproběhne, zařízení je buďto nové nebo je oprava výhodná. Výsledek rovnice je {rounded_replacement_calculation}."

        # Return the replacement calculation and message
        return replacement_calculation, message

class HardwareForm(forms.ModelForm):
    """
    Form for creating or updating hardware data.
    Includes fields for brand name, hardware name, price, and write-off length.
    """
    class Meta:
        model = Hardware
        fields = ['brand_name', 'hw_name', 'hw_price', 'write_off_length']

        labels = {
            "brand_name": "Brand",
            "hw_name": "Název zařízení",
            "hw_price": "Pořizovací cena zařízení",
            "write_off_length": "Doba odpisu zařízení",
        }

        help_texts = {
            "brand_name": "Zadejte brand",
            "hw_name": "Zadejte název zařízení",
            "hw_price": "Zadejte cenu zařízení",
            "write_off_length": "Zadejte dobu odpisu v letech"
        }

    def clean_write_off_length(self):
        """
        Validates the write-off period to ensure it is one of the allowed values (3, 5, or 7 years).

        :raises ValidationError: If the write-off length is not 3, 5, or 7 years.
        :return: Cleaned write-off length.
        """
        write_off_length = self.cleaned_data.get('write_off_length')

        # Ensure the write-off length is either 0, 3, 5, or 7 years
        if write_off_length not in [0, 3, 5, 7]:
            raise ValidationError("Délka odpisu musí být 0, 3, 5 nebo 7 let.")

        return write_off_length

replacement/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, FormView, UpdateView, CreateView, TemplateView, DeleteView, \
    DetailView
from django.contrib import messages

from replacement.forms import ReplacementForm, HardwareForm
from replacement.models import Hardware
from replacement.utils import RedirectToCorrectBrandMixin


class HomePageTemplateView(LoginRequiredMixin, TemplateView):
    """Login requierd view for home page.
    Displays the homepage for logged-in users.
    """
    template_name = "replacement_home_page_template_view.html"

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context


# ***********************************
# Hardware views
# ***********************************

class HardwareDetailListingView(LoginRequiredMixin, DetailView):
    """Login required view for hardware detail page.
    Displays detailed information about a specific hardware item.
    """
    template_name = "hardware_detail_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)

        return context


class HardwareUpdateView(LoginRequiredMixin, RedirectToCorrectBrandMixin, UpdateView):
    """Login required view for hardware update page.
    After submmiting, redirects to correct brand listing page.
    """
    template_name = "hardware_update_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    form_class = HardwareForm
    access_rights = ["editor"]

    def form_valid(self, form):
        """
        Displays a success message when the hardware update is submitted successfully.

        :param form: The form with valid data to update the hardware.
        :return: Redirects to the success URL after form validation.
        """
        messages.success(self.request, f"Stroj byl úspěšně upraven")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context



class HardwareCreateView(LoginRequiredMixin, RedirectToCorrectBrandMixin, CreateView):
    """Login required view for creating hardware page.
    After submmiting, redirects to correct brand listing page.
    """
    template_name = "hardware_create_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    form_class = HardwareForm
    access_rights = ["editor"]

    def form_valid(self, form):
        """Displays a success message when the new hardware is created successfully.

        :param form: The form with valid data to create new hardware.
        :return: Redirects to the success URL after form validation.
        """
        messages.success(self.request, f"Nový stroj byl úspěšně přidán")
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context

class HardwareDeleteView(LoginRequiredMixin, RedirectToCorrectBrandMixin, DeleteView):
    """Login required view for deleting hardware page.
    After submmiting, redirects to correct brand listing page
    """
    template_name = "hardware_delete_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    access_rights = ["editor"]

    def form_valid(self, form):
        """Displays a success message when the hardware is successfully deleted.

        :param form: The form for hardware deletion.
        :return: Redirects to the success URL after deletion.
        """
        messages.success(self.request, f"Stroj byl úspěšně vymazán")
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context

class ReplacementCalculationView(LoginRequiredMixin, FormView):
    """Login required view for calculating if HW needs to be replaced."""
    template_name = 'replacement_calculation_form_page_template.html'
    model = Hardware
    form_class = ReplacementForm
    access_rights = ["editor"]

    def get_context_data(self, **kwargs):
        """
        Adds the hardware details to the context for the replacement calculation.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the hardware data to be used in the calculation.
        """
        context = super().get_context_data(**kwargs)

        hardware_id = self.kwargs.get('pk') # Get hardware ID from URL
        context['hardware'] = get_object_or_404(Hardware, pk=hardware_id) # Fetch hardware by ID
        print(context)
        return context

    def form_valid(self, form):
        """
        Performs the replacement calculation based on the input form data.

        :param form: The form containing user input for the calculation.
        :return: Renders the response with the calculation result.
        """
        hardware_id = self.kwargs.get('pk')
        hardware = get_object_or_404(Hardware, pk=hardware_id)

        replacement_calculation, message = form.calculate(hardware) # Perform the calculation

        context = self.get_context_data(form=form)
        context['replacement_calculation'] = replacement_calculation
        context['message'] = message # Add the calculation result and message to context
        print(message)
        return self.render_to_response(context) # Render the result




# ***********************************
# Brand listing views
# ***********************************


class KfcListingView(LoginRequiredMixin, ListView):
    """Brand listing view, shows Hw of KFC"""
    template_name = "kfc_listing_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    access_rights = ["editor"]

    def get_queryset(self):
        """
        Filters and returns hardware items for the KFC brand.

        :return: Queryset of hardware for KFC and order by hw_name alphabetically.
        """
        return Hardware.objects.filter(brand_name__brand_name="KFC").order_by("hw_name")

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context

class StarbucksListingView(LoginRequiredMixin, ListView):
    """Brand listing view, shows Hw of Starbucks"""
    template_name = "starbucks_listing_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    access_rights = ["editor"]

    def get_queryset(self):
        """
        Filters and returns hardware items for the Starbucks brand.

        :return: Queryset of hardware for Starbucks and order by hw_name alphabetically.
        """
        return Hardware.objects.filter(brand_name__brand_name="Starbucks").order_by("hw_name")

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context

class BurgerkingListingView(LoginRequiredMixin, ListView):
    """Brand listing view, shows Hw of Burger King"""
    template_name = "burger_king_listing_view_page_template.html"
    model = Hardware
    context_object_name = "hardware"
    access_rights = ["editor"]
    brand_name = "Burger King"

    def get_queryset(self):
        """
        Filters and returns hardware items for the Burger King brand.

        :return: Queryset of hardware for Burger King and order by hw_name alphabetically.
        """
        return Hardware.objects.filter(brand_name__brand_name="Burger King").order_by("hw_name")

    def get_context_data(self, **kwargs):
        """
        Adds the user's username to the context for display on the page.

        :param kwargs: Additional context arguments passed to the method.
        :return: Context with the user's username.
        """
        context = super().get_context_data(**kwargs)
        context["user_name"] = self.request.user.username

        return context

replacement/templates/PRAZDNA_SABLONA.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}

{% block bootstrap5_title %}TAB{% endblock %}

{% block hlavni_nadpis %}

{% endblock %}

{% block content %}

{% endblock %}

replacement/templates/base_with_bootstrap.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load bootstrap5 %}

{% block bootstrap5_content %}

<body id="header" class="theme-label-when-dark">

 <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0a3a5c;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Replacement app</a>
        </div>
    </nav>
<div class="container">

        <div class="row mb-3">
            <div class="col">
                <div class="container">
                    <div class="row mt-3"> <!-- urcuje pocet sloupcu -->
                        <div class="col">  <!-- urcuje pocet radku -->

                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col">
            <!-- TADY BUDE MENU -->


                {% block context_menu %}
                    <nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light">
                                <div class="container">
                                    <a class="navbar-brand" href="{% url 'replacement:home-page' %}">Domov</a>
                                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                        <span class="navbar-toggler-icon"></span>
                                    </button>
                                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                        <ul class="navbar-nav">
                                            <li class="nav-item">
                                                <a href="{% url 'replacement:kfc-list' %}" class="nav-link">KFC</a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="{% url 'replacement:sbx-list' %}" class="nav-link">Starbucks</a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="{% url 'replacement:bk-list' %}" class="nav-link">Burger King</a>
                                            </li>
                                            <li class="nav-item">
                                                <a href="{% url 'replacement:ph-list' %}" class="nav-link">Pizza Hut</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>

                {% endblock %}&nbsp;&nbsp;
            </div>
        </div>
<h1 class="mt-3">{% block hlavni_nadpis %}{% endblock %}</h1>
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
        <div id="footer">
            <div class="container-fluid d-flex justify-content-between align-items-center">


                <div class="d-flex justify-content-start align-items-center me-3 ms-3">
                    <div style="margin-right: 15px;">
                        User:&nbsp;&nbsp;
                        {% if user.is_authenticated %}
                            {{ user }}
                        {% else %}
                            Not logged in
                        {% endif %}
                    </div>

                    <div>
                        {% if user.is_authenticated %}
                            <a href="{% url 'logout-yes-no' %}?userid={{ user.pk }}">
                                <button class="btn-sm btn-animace">Logout</button>
                            </a>
                        {% else %}
                            <a href="{% url 'login' %}">
                                <button class="btn-sm btn-animace">Login</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
 </div>
 </div>
{% endblock %}

replacement/templates/hardware_detail_view_page_template.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}

{% block bootstrap5_title %}
    Detail HW
{% endblock %}

{% block hlavni_nadpis %}
    <h3 class="text-center mt-4 mb-4">Detail vybraného stroje</h3>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="card shadow-lg rounded-lg">
        <div class="card-header bg-secondary text-white">
            <h3>Detail stroje: {{ hardware.hw_name }}</h3>
            <div class="d-flex justify-content-end mt-3">
    <a class="btn btn-sm btn-info mx-2 btn-hover" href="{% url 'replacement:replacement-calculation' hardware.pk %}">
        Výpočet replacement
    </a>
    <a class="btn btn-sm btn-light mx-2 btn-hover" href="{% url 'replacement:hw-update' hardware.pk %}?next={{ request.path }}">
        ✎
    </a>
    <a class="btn btn-sm btn-danger mx-2 btn-hover" href="{% url 'replacement:hw-delete' hardware.pk %}?next={{ request.path }}">
        🗑️
    </a>
    </div>
        </div>
        <div class="card-body">
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Název stroje:</div>
                <div class="col">{{ hardware.hw_name }}</div>
            </div>
            <hr>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Brand:</div>
                <div class="col">{{ hardware.brand_name }}</div>
            </div>
            <hr>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Pořizovací cena:</div>
                <div class="col">{{ hardware.hw_price }} Kč</div>
            </div>
            <hr>
            <div class="row my-3">
                <div class="col-3 font-weight-bold">Délka odpisu:</div>
                <div class="col">{{ hardware.write_off_length }} let</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

replacement/templates/hardware_listing_page_view_page_template.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}

{% block bootstrap5_title %}Hardware list{% endblock %}


{% block hlavni_nadpis %}

    Seznam vsech dostupnych zařízení{% endblock %}

{% block content %}

        <!-- first_name last_name_ date_of_birth -->
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">PK</th>
                <th scope="col">Stroj</th>
                <th scope="col">Pořizovací cena</th>
                <th scope="col">Délka odpisu</th>
                <th scope="col" class="text-end">Replacement</th>

            </tr>
            </thead>
            <tbody>
            {% for hardware in hardware %}
                <tr>
                    <td>{{ hardware.pk }}</td>
                    <td>{{ hardware.hw_name }}</td>
                    <td>{{ hardware.hw_price }}</td>
                    <td>{{ hardware.write_off_length }}</td>


                    <td class="text-end">
                        <a class="btn btn-sm btn-info" href="{% url 'replacement:replacement-calculation' hardware.pk %}"> Výpočet replacement</a>
                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock %}

replacement/templates/home_page_template_view.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}

{% block bootstrap5_title %}Replacement app{% endblock %}

{% block hlavni_nadpis %}
    <h3 class="text-center mt-4 mb-4">Domovská stránka</h3>
{% endblock %}


{% block content %}

    <div class="container">
        <p>This is a test content to check visibility.</p>
    </div>

{% endblock %}

replacement/templates/kfc_listing_view_page_template.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_title %}🍗 KFC{% endblock %}

{% block hlavni_nadpis %}
     <h3 class="text-center mt-4 mb-4">🍗 Seznam všech dostupných zařízení KFC 🍗</h3>
{% endblock %}

{% block content %}
{% include 'snippets/create_new_hw_button.html' %}

<table class="table table-dark table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Stroj</th>
                <th scope="col">Pořizovací cena</th>
                <th scope="col">Délka odpisu</th>
                <th scope="col" class="text-end">Replacement</th>
                <th scope="col" class="text-end">Upravit</th>
                <th scope="col" class="text-end">Smazat</th>

            </tr>
            </thead>
            <tbody>
            {% for hardware in hardware %}
                <tr>
                    <td>{{ hardware.pk }}</td>
                    <td><a href="{% url 'replacement:hw-detail' hardware.pk %}" class="link-light">{{ hardware.hw_name }}</a></td>
                    <td>{{ hardware.hw_price }}</td>
                    <td>{{ hardware.write_off_length }}</td>


                    <td class="text-end">
                        <a class="btn btn-sm btn-info btn-animace:hover" href="{% url 'replacement:replacement-calculation' hardware.pk %}"> Výpočet replacement</a>
                    </td>
                    <td class="text-end">
                        <a class="btn btn-sm btn-light" href="{% url 'replacement:hw-update' hardware.pk %}?next={{ request.path }}">✎</a>
                    </td>
                    <td class="text-end">
                        <a class="btn btn-sm btn-danger" href="{% url 'replacement:hw-delete' hardware.pk %}?next={{ request.path }}">🗑️</a>
                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock %}

replacement/templates/pizza_hut_listing_view_page_template.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_title %}🍕 Pizza Hut{% endblock %}

{% block hlavni_nadpis %}
     <h3 class="text-center mt-4 mb-4">🍕 Seznam všech dostupných zařízení Pizza Hut 🍕</h3>
{% endblock %}

{% block content %}
{% include 'snippets/create_new_hw_button.html' %}

            <table class="table table-dark table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Stroj</th>
                <th scope="col">Pořizovací cena</th>
                <th scope="col">Délka odpisu</th>
                <th scope="col" class="text-end">Replacement</th>
                <th scope="col" class="text-end">Upravit</th>
                <th scope="col" class="text-end">Smazat</th>

            </tr>
            </thead>
            <tbody>
            {% for hardware in hardware %}
                <tr>
                    <td>{{ hardware.pk }}</td>
                    <td><a href="{% url 'replacement:hw-detail' hardware.pk %}" class="link-light">{{ hardware.hw_name }}</a></td>
                    <td>{{ hardware.hw_price }}</td>
                    <td>{{ hardware.write_off_length }}</td>


                    <td class="text-end">
                        <a class="btn btn-sm btn-info btn-animace:hover" href="{% url 'replacement:replacement-calculation' hardware.pk %}">Výpočet replacement</a>
                    </td>
                    <td class="text-end">
                        <a class="btn btn-sm btn-animace:hover btn-light" href="{% url 'replacement:hw-update' hardware.pk %}?next={{ request.path }}">✎</a>
                    </td>
                     <td class="text-end">
                        <a class="btn btn-sm btn-danger" href="{% url 'replacement:hw-delete' hardware.pk %}?next={{ request.path }}">🗑️</a>
                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}

replacement/templates/starbucks_listing_view_page_template.html
{% extends "base_with_bootstrap.html" %}
{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_title %} ☕ Starbucks{% endblock %}

{% block hlavni_nadpis %}
     <h3 class="text-center mt-4 mb-4">☕ Seznam všech dostupných zařízení Starbucks ☕</h3>
{% endblock %}

{% block content %}
{% include 'snippets/create_new_hw_button.html' %}

<table class="table table-dark table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Stroj</th>
                <th scope="col">Pořizovací cena</th>
                <th scope="col">Délka odpisu</th>
                <th scope="col" class="text-end">Replacement</th>
                <th scope="col" class="text-end">Upravit</th>
                <th scope="col" class="text-end">Smazat</th>
            </tr>
            </thead>
            <tbody>
            {% for hardware in hardware %}
                <tr>
                    <td>{{ hardware.pk }}</td>
                    <td><a href="{% url 'replacement:hw-detail' hardware.pk %}" class="link-light">{{ hardware.hw_name }}</a></td>
                    <td>{{ hardware.hw_price }}</td>
                    <td>{{ hardware.write_off_length }}</td>


                    <td class="text-end">
                        <a class="btn btn-sm btn-info" href="{% url 'replacement:replacement-calculation' hardware.pk %}"> Výpočet replacement</a>
                    </td>
                    <td class="text-end">
                        <a class="btn btn-sm btn-light" href="{% url 'replacement:hw-update' hardware.pk %}?next={{ request.path }}">✎</a>
                    </td>
                     <td class="text-end">
                        <a class="btn btn-sm btn-danger" href="{% url 'replacement:hw-delete' hardware.pk %}?next={{ request.path }}">🗑️</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock %}